-- =============================================================================
-- MeFamous — Phase 7: Provider-agnostic services/orders
--
-- Before this migration, `services.id` WAS literally Owlet's numeric
-- service id, and `orders.owlet_order_id` assumed every provider hands
-- back a bigint order id. That hardcodes Owlet into the schema itself.
-- This migration makes `services.id` a plain internal identifier and adds
-- (provider, provider_service_id) so a service can come from any
-- provider, and adds `orders.provider` so historical orders remember who
-- actually fulfilled them even after the active provider is switched.
--
-- Run AFTER 0001–0004. Safe to re-run.
-- =============================================================================

-- ── services: decouple internal id from the provider's own id ──────────────
alter table public.services add column if not exists provider text not null default 'owlet';
alter table public.services add column if not exists provider_service_id text;

update public.services set provider_service_id = id::text where provider_service_id is null;
alter table public.services alter column provider_service_id set not null;

-- Turn the existing plain bigint id into a proper auto-incrementing
-- internal identifier (it happened to start out equal to Owlet's id —
-- that was never structural, just how the very first sync populated it).
do $$
declare
  v_next bigint;
begin
  select coalesce(max(id), 0) + 1 into v_next from public.services;
  execute format('alter table public.services alter column id add generated by default as identity (start with %s)', v_next);
exception when duplicate_object then
  -- Already converted by a previous run of this migration.
  null;
end $$;

drop index if exists services_provider_service_unique;
create unique index services_provider_service_unique
  on public.services (provider, provider_service_id);

create index if not exists services_provider_idx on public.services (provider);

alter table public.services rename column owlet_type to provider_type;

-- ── orders: remember which provider actually fulfilled each order ──────────
alter table public.orders add column if not exists provider text;

alter table public.orders
  alter column owlet_order_id type text using owlet_order_id::text;

alter table public.orders rename column owlet_order_id to provider_order_id;

update public.orders o
  set provider = s.provider
  from public.services s
  where o.service_id = s.id and o.provider is null;

update public.orders set provider = 'owlet' where provider is null;
alter table public.orders alter column provider set not null;
alter table public.orders alter column provider set default 'owlet';

create index if not exists orders_provider_idx on public.orders (provider);

-- ── place_order: stamp the order with the service's current provider ───────
create or replace function public.place_order(
  p_service_id bigint,
  p_link text,
  p_quantity integer,
  p_price numeric
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_balance numeric(12, 2);
  v_service public.services%rowtype;
  v_order public.orders%rowtype;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if p_price <= 0 then
    raise exception 'Order price must be greater than zero';
  end if;

  select * into v_service from public.services where id = p_service_id and is_active = true;
  if not found then
    raise exception 'Service % is not available', p_service_id;
  end if;

  if p_quantity < v_service.min_quantity or p_quantity > v_service.max_quantity then
    raise exception 'Quantity must be between % and %', v_service.min_quantity, v_service.max_quantity;
  end if;

  select wallet_balance into v_balance from public.profiles where id = v_user_id for update;

  if v_balance is null then
    raise exception 'Profile not found for current user';
  end if;

  if v_balance < p_price then
    raise exception 'Insufficient wallet balance';
  end if;

  update public.profiles set wallet_balance = wallet_balance - p_price where id = v_user_id;

  insert into public.orders (user_id, service_id, provider, link, quantity, price_charged, status)
  values (v_user_id, p_service_id, v_service.provider, p_link, p_quantity, p_price, 'pending')
  returning * into v_order;

  return v_order;
end;
$$;

-- ── confirm_order: provider order id is now text (providers vary) ──────────
create or replace function public.confirm_order(p_order_id uuid, p_provider_order_id text)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
begin
  select * into v_order from public.orders where id = p_order_id;
  if not found then
    raise exception 'Order % not found', p_order_id;
  end if;

  if auth.role() <> 'service_role' and not public.is_admin() and v_order.user_id <> auth.uid() then
    raise exception 'Not permitted';
  end if;

  update public.orders
    set provider_order_id = p_provider_order_id, status = 'submitted'
    where id = p_order_id
    returning * into v_order;

  return v_order;
end;
$$;

-- ── provider_api_logs — renamed from owlet_api_logs, now tags the provider ──
alter table public.owlet_api_logs add column if not exists provider text not null default 'owlet';
alter table public.owlet_api_logs rename to provider_api_logs;

drop policy if exists owlet_api_logs_select_admin on public.provider_api_logs;
drop policy if exists provider_api_logs_select_admin on public.provider_api_logs;
create policy provider_api_logs_select_admin
  on public.provider_api_logs for select
  using (public.is_admin());

create index if not exists provider_api_logs_provider_idx on public.provider_api_logs (provider);

-- ── active_provider setting — which adapter new orders/syncs use ───────────
insert into public.app_settings (key, value)
values ('active_provider', '"owlet"'::jsonb)
on conflict (key) do nothing;

-- Genericize the auto-sync toggle name too — it applies to whichever
-- provider is active, not specifically Owlet.
update public.app_settings set key = 'provider_auto_sync_enabled'
  where key = 'owlet_auto_sync_enabled'
  and not exists (select 1 from public.app_settings where key = 'provider_auto_sync_enabled');

insert into public.app_settings (key, value)
values ('provider_auto_sync_enabled', 'false'::jsonb)
on conflict (key) do nothing;
